<%inherit file="_sidebar_rules.mako"/>

<%def name="title()">Backgrounds</%def>

<%def name="body()">

  <script>
  $(function() {
    var tabs = $( "#tabs" ).tabs();
    tabs.find( ".ui-tabs-nav" ).sortable({
      axis: "x",
      stop: function() {
        tabs.tabs( "refresh" );
      }
    });
  });
  </script>

<div id="tabs">
  <ul>
    <li><a href="#tabs-1">K Piercing</a></li>
    <li><a href="#tabs-2">K Slashing</a></li>
    <li><a href="#tabs-3">K Impact</a></li>
    <li><a href="#tabs-4">Chemical</a></li>
    <li><a href="#tabs-5">Cold</a></li>
    <li><a href="#tabs-6">Electricity</a></li>
    <li><a href="#tabs-7">Explosive</a></li>
    <li><a href="#tabs-8">Implosive</a></li>
    <li><a href="#tabs-9">Heat</a></li>
    <li><a href="#tabs-10">Radiation</a></li>
</ul>
<div id="tabs-1">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Head</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Brain</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Both Eyes</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Left Eye</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Right Eye</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Right Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Mouth</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Nose</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Neck</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Scalp</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Torso</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Heart</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Spine</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Lung</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Liver </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Stomach</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Misc organs</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-2">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Head</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Brain</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Both Eyes</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Mouth</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Nose</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Neck</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Scalp</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Torso</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Heart</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Spine</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Lung</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Liver </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Stomach</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Misc organs</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-3">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Head</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Brain</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Both Eyes</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Left Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Mouth</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Nose</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Neck</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Scalp</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Torso</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Heart</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Spine</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Lung</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Liver </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Stomach</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Misc organs</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-4">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Head</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-5">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Head</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>  
</div>
<div id="tabs-6">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Head</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table> 
</div>
<div id="tabs-7">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Head</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Heart</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-8">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td></tr>
 <tr><td>Head</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-9">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Head</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Brain</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Both Eyes</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Eye</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Right Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Left Ear</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Mouth</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Nose</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Neck</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Scalp</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Spine</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Lung</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Liver </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Stomach</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Misc organs</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Elbow</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Forearm</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Hand</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Knee </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Shin </td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr>
 <tr><td>Feet</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td><td class="unharmed">UNHARMED</td></tr></table>
</div>
<div id="tabs-10">
<table class="damage-table">
<tr class="damage-firstrow"><th></th><th>12 to 10</th><th>9 to 7</th><th>6 or 5</th><th>4 or 3</th><th>2 or 1</th><th>0 to -2</th><th>-3 to -5</th></tr>
 <tr><td>Body</td><td class="dead">DEAD</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td></tr>
 <tr><td>Head</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Brain</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Both Eyes</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Eye</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Right Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Left Ear</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Mouth</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Nose</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Neck</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Scalp</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Torso</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Heart</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Spine</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Lung</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Liver </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Stomach</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Misc organs</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Upper arm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Elbow</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Forearm</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hand</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Leg</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Hip</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Knee </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Shin </td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr>
 <tr><td>Feet</td><td class="mortal">MORTAL</td><td class="deadly">DEADLY</td><td class="serious">SERIOUS</td><td class="severe">SEVERE</td><td class="medium">MEDIUM</td><td class="light">LIGHT</td><td class="superficial">SUPERFICIAL</td></tr></table>
</div>
</div>
</%def>