<%inherit file="_sidebar_rules.mako"/>

<%def name="title()">Constitution Tables</%def>

<%def name="body()">

    <h3>Constitution Tables</h3>
    
<P><table class="full-table">
    <Caption>Stamina Task Target Numbers</Caption>
   <tr>
      <th>Base Target Number</th>
      <th>Toxin/Pathogen/Illness Grade</th>
      <th>CONS Booster</th>
      <th>Crit Rating Modifier</th>
      <th>Percentage Healing Time</th>
   </tr>
   <tr>
      <td>3</td>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>100%</td>
   </tr>
   <tr>
      <td>6</td>
      <td>1</td>
      <td>1</td>
      <td>-1</td>
      <td>96%</td>
   </tr>
   <tr>
      <td>12</td>
      <td>2</td>
      <td>2</td>
      <td>-1</td>
      <td>93%</td>
   </tr>
   <tr>
      <td>18</td>
      <td>3</td>
      <td>3</td>
      <td>-1</td>
      <td>90%</td>
   </tr>
   <tr>
      <td>24</td>
      <td>4</td>
      <td>4</td>
      <td>-2</td>
      <td>87%</td>
   </tr>
   <tr>
      <td>30</td>
      <td>5</td>
      <td>5</td>
      <td>-2</td>
      <td>84%</td>
   </tr>
   <tr>
      <td>36</td>
      <td>6</td>
      <td>6</td>
      <td>-2</td>
      <td>81%</td>
   </tr>
   <tr>
      <td></td>
      <td>7</td>
      <td>7</td>
      <td>-3</td>
      <td>78%</td>
   </tr>
   <tr>
      <td></td>
      <td>8</td>
      <td>8</td>
      <td>-3</td>
      <td>75%</td>
   </tr>
   <tr>
      <td></td>
      <td>9</td>
      <td>9</td>
      <td>-3</td>
      <td>72%</td>
   </tr>
   <tr>
      <td></td>
      <td>10</td>
      <td>10</td>
      <td>-4</td>
      <td>69%</td>
   </tr>
   <tr>
      <td></td>
      <td>11</td>
      <td>11</td>
      <td>-4</td>
      <td>66%</td>
   </tr>
   <tr>
      <td></td>
      <td>12</td>
      <td>12</td>
      <td>-4</td>
      <td>63%</td>
   </tr>
   <tr>
      <td></td>
      <td>13</td>
      <td>13</td>
      <td>-5</td>
      <td>60%</td>
   </tr>
   <tr>
      <td></td>
      <td>14</td>
      <td>14</td>
      <td>-5</td>
      <td>57%</td>
   </tr>
   <tr>
      <td></td>
      <td>15</td>
      <td>15</td>
      <td>-5</td>
      <td>54%</td>
   </tr>
   <tr>
      <td></td>
      <td>16</td>
      <td>16</td>
      <td>-6</td>
      <td>51%</td>
   </tr>
   <tr>
      <td></td>
      <td>17</td>
      <td>17</td>
      <td>-6</td>
      <td>48%</td>
   </tr>
   <tr>
      <td></td>
      <td>18</td>
      <td>18</td>
      <td>-6</td>
      <td>45%</td>
   </tr>
   <tr>
      <td></td>
      <td>19</td>
      <td>19</td>
      <td>-7</td>
      <td>42%</td>
   </tr>
   <tr>
      <td></td>
      <td>20</td>
      <td>20</td>
      <td>-7</td>
      <td>39%</td>
   </tr>
   <tr>
      <td></td>
      <td>21</td>
      <td>21</td>
      <td>-7</td>
      <td>36%</td>
   </tr>
   <tr>
      <td></td>
      <td>22</td>
      <td>22</td>
      <td>-8</td>
      <td>33%</td>
   </tr>
   <tr>
      <td></td>
      <td>23</td>
      <td>23</td>
      <td>-8</td>
      <td>30%</td>
   </tr>
   <tr>
      <td></td>
      <td>24</td>
      <td>24</td>
      <td>-8</td>
      <td>27%</td>
   </tr>
   <tr>
      <td></td>
      <td>25</td>
      <td>25</td>
      <td>-9</td>
      <td>24%</td>
   </tr>
   <tr>
      <td></td>
      <td>26</td>
      <td>26</td>
      <td>-9</td>
      <td>21%</td>
   </tr>
   <tr>
      <td></td>
      <td>27</td>
      <td>27</td>
      <td>-9</td>
      <td>18%</td>
   </tr>
   <tr>
      <td></td>
      <td>28</td>
      <td>28</td>
      <td>-10</td>
      <td>15%</td>
   </tr>
   <tr>
      <td></td>
      <td>29</td>
      <td>29</td>
      <td>-10</td>
      <td>12%</td>
   </tr>
   <tr>
      <td></td>
      <td>30</td>
      <td>30</td>
      <td>-11</td>
      <td>9%</td>
   </tr>
   <tr>
      <td></td>
      <td>31</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
   <tr>
      <td></td>
      <td>32</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
   <tr>
      <td></td>
      <td>33</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
   <tr>
      <td></td>
      <td>34</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
   <tr>
      <td></td>
      <td>35</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
   <tr>
      <td></td>
      <td>36</td>
      <td></td>
      <td></td>
      <td></td>
   </tr>
</table></p>
</%def>
